[bindings.kotlin]
package_name = "io.nativeblocks.core.engine"
cdylib_name = "core"
generate_immutable_records = true
disable_java_cleaner = true

[bindings.swift]
module_name = "NativeblocksCoreEngine"
generate_immutable_records = true
